# Generated by Django 4.1.4 on 2022-12-30 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dir_mst',
            fields=[
                ('dirpath', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('dirvolume', models.IntegerField()),
                ('dirmanager', models.CharField(max_length=50)),
                ('dirphase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='access_mst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('authority', models.CharField(choices=[('F', 'フルコントロール'), ('W', '更新権'), ('R', '検索権')], max_length=50)),
                ('dirpath', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dir_mg_sys.dir_mst')),
            ],
        ),
    ]
