# Generated by Django 4.1.4 on 2023-01-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dir_mg_sys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dir_mst',
            old_name='dirmanager_id',
            new_name='dirmanager',
        ),
    ]
