# Generated by Django 4.1.4 on 2023-01-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dir_mg_sys', '0003_alter_dir_mst_dirmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_organaization',
            old_name='group_id',
            new_name='group_mst',
        ),
        migrations.RenameField(
            model_name='group_organaization',
            old_name='user_id',
            new_name='user_mst',
        ),
    ]
