# Generated by Django 4.1.4 on 2023-01-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dir_mg_sys', '0004_rename_group_id_group_organaization_group_mst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_organaization',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='group_organaization',
            name='user_name',
        ),
    ]
