# Generated by Django 4.1.4 on 2023-01-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir_mg_sys', '0004_remove_dir_mst_dirparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dir_mst',
            name='dirparent',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
