# Generated by Django 4.1.4 on 2023-01-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir_mg_sys', '0006_remove_dir_mst_dirphase'),
    ]

    operations = [
        migrations.CreateModel(
            name='first_dir_mst',
            fields=[
                ('dirpath', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('dirvolume', models.IntegerField()),
                ('dirmanager', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='second_dir_mst',
            fields=[
                ('dirpath', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('dirvolume', models.IntegerField()),
                ('dirmanager', models.CharField(max_length=50)),
                ('dirparent', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='third_dir_mst',
            fields=[
                ('dirpath', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('dirvolume', models.IntegerField()),
                ('dirmanager', models.CharField(max_length=50)),
                ('dirparent', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='dir_mst',
            new_name='forth_dir_mst',
        ),
        migrations.AlterField(
            model_name='access_mst',
            name='dirpath',
            field=models.CharField(max_length=1000),
        ),
    ]
