# Generated by Django 4.1.4 on 2023-01-01 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dir_mg_sys', '0007_first_dir_mst_second_dir_mst_third_dir_mst_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dir_mst',
            fields=[
                ('dirpath', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('dirvolume', models.IntegerField()),
                ('dirmanager', models.CharField(max_length=50)),
                ('dirphase', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='first_dir_mst',
        ),
        migrations.DeleteModel(
            name='forth_dir_mst',
        ),
        migrations.DeleteModel(
            name='second_dir_mst',
        ),
        migrations.DeleteModel(
            name='third_dir_mst',
        ),
        migrations.AlterField(
            model_name='access_mst',
            name='dirpath',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dir_mg_sys.dir_mst'),
        ),
    ]
